### ISSUE TITLE
error when loading

### ISSUE THREAD

**Issue by KyleBax** [KyleBax/AI-GM#42]
game can be layed when creating new, doesn't load a saved game
press Y to start a new campaign
n
Unexpected type "AI_GM.Campaign" in assembly "AI-GM, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
In safe mode you should specify the expected types in the expectedCustomTypes parameter of the deserialization methods.
If assembly has a partial name or its identity has changed since the serialization you can use the ForwardedTypesSerializationBinder if you set its SafeMode to true.
System.Runtime.Serialization.SerializationException: Unexpected type "AI_GM.Campaign" in assembly "AI-GM, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
In safe mode you should specify the expected types in the expectedCustomTypes parameter of the deserialization methods.
If assembly has a partial name or its identity has changed since the serialization you can use the ForwardedTypesSerializationBinder if you set its SafeMode to true.
   at KGySoft.Throw.SerializationException(String message)
   at KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializationManager.ReadNewTypeWithAssembly(String assemblyName, String typeName)
   at KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializationManager.ReadType(BinaryReader br, Boolean allowOpenTypes)
   at KGySoft.Serialization.Binary.BinarySerializationFormatter.DataTypeDescriptor.GetElementType(DataTypes dt, BinaryReader br, DeserializationManager manager, Boolean allowOpenTypes, DataTypeDescriptor& existingDescriptor)
   at KGySoft.Serialization.Binary.BinarySerializationFormatter.DataTypeDescriptor.DecodeType(BinaryReader br, DeserializationManager manager, Boolean allowOpenTypes)
   at KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializationManager.ReadRoot(BinaryReader br)
   at KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializationManager.Deserialize(BinaryReader br)
   at KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializeFromStream(Stream stream)
   at AI_GM.SaveLoad.DeserializeCampaign() in C:\Users\kyle-\source\repos\KyleBax\AI-GM\SaveLoad.cs:line 40

**Comment by KyleBax** [comment]
assumention: the 4xternal binaray formatter has a safe mode option -> investigate
