### ISSUE TITLE
Game doesn't work when not on my pc

### ISSUE THREAD

**Issue by KyleBax** [KyleBax/AI-GM#60]
Make it so the game can be played on other computers
this occurs when attempting to save or load
Unhandled exception. System.TypeInitializationException: The type initializer for 'AI_GM.FilePaths' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at AI_GM.FilePaths..cctor() in C:\Users\kyle-\source\repos\KyleBax\AI-GM\FilePaths.cs:line 23
   --- End of inner exception stack trace ---
   at AI_GM.SaveLoad.DeserializeCampaign() in C:\Users\kyle-\source\repos\KyleBax\AI-GM\SaveLoad.cs:line 26
   at AI_GM.Program.Main() in C:\Users\kyle-\source\repos\KyleBax\AI-GM\Program.cs:line 23

**Comment by KyleBax** [comment]
it seems to work intimitently

**Comment by KyleBax** [comment]
it is targetting user\kyle-\... needs to be rewritten so that it no longer searches for that

**Comment by KyleBax** [comment]
It's only when I publish the game, moving back in to Todo
